[tools]
python = "latest"
neovim = "latest"
peco = "latest"
ghq = "latest"
zoxide = "latest"
rye = "latest"
pipx = "latest"
"pipx:ruff" = "latest"
"pipx:uv" = "latest"
bat = "latest"
ripgrep = "latest"
node = "latest"
tree-sitter = "latest"
fd = "latest"
usage = "latest"
exa = "latest"
aria2 = "latest"
duf = "latest"
jq = "latest"
rust = "latest"
"cargo:tre" = "latest"
shellcheck = "latest"
shfmt = "latest"
starship = "1.19.0"
"pipx:httpie" = "latest"
"pipx:podman-compose" = "latest"
fzf = "latest"
go = "latest"
"npm:diff-so-fancy" = "latest"
lazygit = "latest"

[settings]
experimental = true
legacy_version_file = false
