[tools]
python = "latest"
neovim = "nightly"
peco = "latest"
ghq = "latest"
zoxide = "latest"
rye = "latest"
"pipx:ruff" = "latest"
bat = "latest"
ripgrep = "latest"
node = "latest"
tree-sitter = "latest"
fd = "latest"
aria2 = "latest"
duf = "latest"
jq = "latest"
rust = "latest"
"cargo:tre" = "latest"
shellcheck = "latest"
shfmt = "latest"
starship = "1.19.0"
"pipx:httpie" = "latest"
fzf = "latest"
go = "latest"
"npm:diff-so-fancy" = "latest"
lazygit = "latest"
"pipx:md2pdf" = "latest"
"pipx:podman-compose" = "latest"
uv = "latest"
bun = "latest"
"npm:markdownlint-cli" = "latest"
"cargo:eza" = "latest"
usage = "latest"
java = "21"
"cargo:csview" = "latest"
"cargo:viu" = "latest"
"go:github.com/gokcehan/lf" = "latest"
"pipx:art" = "latest"
"cargo:lolcrab" = "latest"
"cargo:pay-respects" = "latest"
"cargo:du-dust" = "latest"
"cargo:cargo-clean-all" = "latest"
sqlite = "latest"
"cargo:create-tauri-app" = "latest"
"cargo:tauri-cli" = "latest"
"npm:azure-pipelines-language-server" = "latest"
"pipx:terminaltexteffects" = "latest"
"npm:@mermaid-js/mermaid-cli" = "latest"
"npm:@modelcontextprotocol/inspector" = "latest"
"pipx:lizard" = "latest"
"npm:mcp-hub" = "4.2.1"

[settings]
experimental = true
legacy_version_file = false

[settings.pipx]
uvx = true

[settings.npm]
bun = true
