[tools]
python = "latest"
neovim = "nightly"
peco = "latest"
ghq = "latest"
zoxide = "latest"
rye = "latest"
pipx = "latest"
"pipx:ruff" = "latest"
bat = "latest"
ripgrep = "latest"
node = "latest"
tree-sitter = "latest"
fd = "latest"
aria2 = "latest"
duf = "latest"
jq = "latest"
rust = "latest"
"cargo:tre" = "latest"
shellcheck = "latest"
shfmt = "latest"
starship = "1.19.0"
"pipx:httpie" = "latest"
fzf = "latest"
go = "latest"
"npm:diff-so-fancy" = "latest"
lazygit = "latest"
"pipx:md2pdf" = "latest"
"pipx:podman-compose" = "latest"
uv = "latest"
bun = "latest"
"npm:markdownlint-cli" = "latest"
"cargo:eza" = "latest"
usage = "latest"
java = "21"
"cargo:csview" = "latest"
"cargo:viu" = "latest"

[settings]
experimental = true
legacy_version_file = false

[settings.pipx]
uvx = true

[settings.npm]
bun = true
